### ISSUE TITLE
To clarify a few points...

### ISSUE THREAD

**Issue by Stono** [rdsubhas/java-istio#1]
A few things, this isn't about java9/java11 - it's more broadly around http1.1 -> http2.0 upgrades 
(it can affect java8 to if you upgrade certain libraries).

It seems to more specifically be to do with a `Connection HTTP2-Settings` request being sent, yet omitting the mandatory `HTTP2-Settings` field:

works:
```
[atcloud@sauron-graphql-server-57856b599d-p47pt graphql-server]$ curl -v -H "Upgrade: h2c" app.owner-reviews-service
* About to connect() to app.owner-reviews-service port 80 (#0)
*   Trying 10.192.34.183...
* Connected to app.owner-reviews-service (10.192.34.183) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: app.owner-reviews-service
> Accept: */*
> Upgrade: h2c
>
< HTTP/1.1 200 OK
< originating-request-identifier: 16E30A82C81F4DAABCE3CB00B8519656
< request-identifier: 16E30A82C81F4DAABCE3CB00B8519656
< content-type: text/plain;charset=UTF-8
< content-length: 4
< date: Tue, 20 Aug 2019 17:36:58 GMT
< x-envoy-upstream-service-time: 5
< server: envoy
<
```

fails:
```
[atcloud@sauron-graphql-server-57856b599d-p47pt graphql-server]$ curl -v -H "Connection: Upgrade, HTTP2-Settings" -H "Upgrade: h2c" app.owner-reviews-service
* About to connect() to app.owner-reviews-service port 80 (#0)
*   Trying 10.192.34.183...
* Connected to app.owner-reviews-service (10.192.34.183) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: app.owner-reviews-service
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
>
< HTTP/1.1 403 Forbidden
< date: Tue, 20 Aug 2019 17:37:20 GMT
< server: envoy
< connection: close
< content-length: 0
<
```

It seems like this is more of an envoy problem, than istio.  It looks like envoy can't really handle h2upgrades, as can be tracked in:

 - https://github.com/envoyproxy/envoy/issues/6972
 - https://github.com/envoyproxy/envoy/issues/1502
 - https://github.com/envoyproxy/envoy/issues/7973
 - and mostly https://github.com/envoyproxy/envoy/issues/7161

**Comment by rdsubhas** [comment]
> It seems to more specifically be to do with a `Connection HTTP2-Settings` request being sent, yet omitting the mandatory `HTTP2-Settings` field

This is not true. Even if you include the http2-settings header, it will break. Easiest way is to run curl -vvv --http2.

This is a case of breaking the spec.

I will print the curl --http2 *and* -H http2-settings output with 403 shortly.

**Comment by rdsubhas** [comment]
@Stono – Here is the confirmation. I'm closing your issue as invalid.

To reproduce it exactly, please follow the steps in the README. I will repeat here for your info:

* Create a dummy GKE cluster, k8s 1.13, istio 1.1.7, mTLS permissive
* Run the super simple echo server and client in this repo: `kubectl apply -f "https://raw.githubusercontent.com/rdsubhas/java-istio/master/k8s.yaml"`
* Do the curl:

```
$> curl -vvv --http2 "$ECHO_SERVER_URL"
*   Trying 10.xx.xx.xx...
* TCP_NODELAY set
* Connected to echo-server.echo-server (10.xx.xx.xx) port 8081 (#0)
> GET / HTTP/1.1
> Host: echo-server.echo-server:8081
> User-Agent: curl/7.52.1
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAARAAAAA
> 
< HTTP/1.1 403 Forbidden
< date: Thu, 22 Aug 2019 08:27:32 GMT
< server: istio-envoy
< connection: close
< content-length: 0
< 
* Curl_http_done: called premature == 0
* Closing connection 0
```

Note the `HTTP2-Settings` headers **are sent** and still reproduce same error.

Secondly,

> It seems like this is more of an envoy problem, than istio.

**istio is the package**. And especially envoy is the installed default and global de-facto used data plane. If the package's default & de-facto is broken, then the package is broken. No finger pointing.

**Comment by rdsubhas** [comment]
Closed as wrong info.
